[tool.poetry]
name = "mptreasury"
version = "0.1.0"
description = ""
authors = ["crpier <crpier42@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.9.0"
sqlmodel = "^0.0.6"
alembic = "^1.7.7"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-memray = "^1.0.0"
memray = "^1.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
markers = [
  "unit: self explanatory I think",
  "component: self explanatory I think",
  "e2e: self explanatory I think",
]

